### ISSUE TITLE
Character array is missing "e" notation exponential mark

### ISSUE THREAD

**Issue by jvanderwee** [apollographql/apollo-kotlin-adapters#27]
When updating to 0.0.4 we get this exception thrown in tests using data builders for queries with BigDecimal fields:

```
Character array is missing "e" notation exponential mark.
java.lang.NumberFormatException: Character array is missing "e" notation exponential mark.
	at java.base/java.math.BigDecimal.<init>(Unknown Source)
	at java.base/java.math.BigDecimal.<init>(Unknown Source)
	at java.base/java.math.BigDecimal.<init>(Unknown Source)
	at com.apollographql.adapter.core.BigDecimalAdapter.fromJson(BigDecimal.kt:14)
```

**Comment by martinbonnin** [comment]
Thanks for reporting this. I believe https://github.com/apollographql/apollo-kotlin-adapters/commit/d2ccdecd37bd2b25dfa74f1c472278b6757f6e7e might be the issue although it mostly changes writing `BigDecimal`, not reading them. 

Can you share your data builder and fake resolver?

**Comment by jvanderwee** [comment]
Data builder:
```
UserReferralQuery.Data(resolver = FakeApolloResolver()) {
    userReferralTotal = buildReferralTotalType {
        value = BigDecimal.valueOf(20)
        currency = "GBP"
    }
},
```

Fake resolver:
```
class FakeApolloResolver : FakeResolver {
    private val delegate = DefaultFakeResolver(__Schema.all)

    override fun resolveLeaf(context: FakeResolverContext): Any {
        val fieldName = context.mergedField.type.rawType().name
        return when (fieldName) {
            "Decimal" -> BigDecimal.TEN
            else -> delegate.resolveLeaf(context)
        }
    }

    override fun resolveListSize(context: FakeResolverContext): Int {
        return delegate.resolveListSize(context)
    }

    override fun resolveMaybeNull(context: FakeResolverContext): Boolean {
        return delegate.resolveMaybeNull(context)
    }

    override fun resolveTypename(context: FakeResolverContext): String {
        return delegate.resolveTypename(context)
    }

    override fun stableIdForObject(
        obj: Map<String, Any?>,
        mergedField: CompiledField,
    ): String? {
        return delegate.stableIdForObject(obj, mergedField)
    }
}
```

**Comment by martinbonnin** [comment]
Thanks for this, I can reproduce. Will look into this

**Comment by martinbonnin** [comment]
Fix is [here](https://github.com/apollographql/apollo-kotlin/pull/6141), it'll require a new version of Apollo Kotlin. In the meantime, feel free to stay on `0.0.3`. Apologies foor the inconvenience and thanks for catching this 🙏

**Comment by martinbonnin** [comment]
This should be all good now, closing.
